#!/bin/bash

cat << ASDF > /app/nginx.conf
worker_processes auto;
pid /app/nginx.pid;
daemon off;

events {
    worker_connections 4096;
    multi_accept on;
    use epoll;
}

http {

    ##
    # Basic Settings
    ##

    sendfile on;
    sendfile_max_chunk 1m;
    tcp_nopush on;
    tcp_nodelay on;
    keepalive_timeout 65;
    types_hash_max_size 2048;
    # server_tokens off;

    # server_names_hash_bucket_size 64;
    # server_name_in_redirect off;

    include /usr/local/openresty/nginx/conf/mime.types;
    default_type application/octet-stream;

    ##
    # SSL Settings
    ##

    ssl_protocols TLSv1 TLSv1.1 TLSv1.2; # Dropping SSLv3, ref: POODLE
    ssl_prefer_server_ciphers on;

    ##
    # Logging Settings
    ##

    access_log /dev/null;
    error_log /dev/stdout debug;

    ##
    # Gzip Settings
    ##

    gzip on;
    gzip_disable "msie6";

    gzip_vary on;
    gzip_proxied any;
    gzip_comp_level 6;
    gzip_buffers 16 8k;
    gzip_http_version 1.1;
    gzip_types text/plain text/css application/json application/javascript text/xml application/xml application/xml+rss text/javascript;

    proxy_read_timeout 7d;

    server{
        listen $PORT default_server;

        location / {
            access_by_lua_block {
              ngx.log(ngx.NOTICE, "--------------------------> localhost:3000 + host: " .. ngx.var.http_host)
            }
            proxy_http_version 1.1;
            proxy_pass http://localhost:3000;
            proxy_set_header  X-Real-IP        \$remote_addr;
            proxy_set_header  X-Forwarded-For  \$proxy_add_x_forwarded_for;
            proxy_set_header  Host             \$http_host;
            proxy_redirect    off;

        }
    }

    server {
      listen unix:/tmp/asdf.sock default_server;

      location / {
        access_by_lua_block {
          ngx.log(ngx.NOTICE, "--------------------------> asdf.sock + host: " .. ngx.var.http_host)
        }
        proxy_http_version 1.1;
        proxy_redirect off;
        proxy_set_header Authorization qazwsx;
        proxy_pass http://polar-dawn-55181.herokuapp.com;
      }
    }

    server {
      listen 127.0.1.4:4444 default_server;

      location / {
        access_by_lua_block {
          ngx.log(ngx.NOTICE, "--------------------------> 4444 + host: " .. ngx.var.http_host)
        }

        proxy_redirect off;
        proxy_set_header X-Forwarded-For \$proxy_add_x_forwarded_for;
        proxy_set_header Authorization qazwsx;
        proxy_set_header Host polar-dawn-55181.herokuapp.com;
        proxy_pass http://polar-dawn-55181.herokuapp.com;
      }
    }
}

ASDF

echo "starting supervisor"
exec /usr/bin/supervisord -c /app/supervisord.conf

